### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by jayvdb** [heynemann/preggy#32]
Please add a LICENSE file to the repo, and include it in the sdists uploaded to PyPI.

**Comment by jayvdb** [comment]
Typically this is done by creating a `MANIFEST.in`, with rules for which files to include and which to exclude.

However I believe in the next release it can also be done by configuring setuptools a little. See [pypa/setuptools#1636](https://github.com/pypa/setuptools/issues/1636)

**Comment by MeggyCal** [comment]
Thanks a lot for adding it! Could you please also provide it in the PyPI tarball?
